language: python
python: "3.6"

notifications:      # 邮箱通知
  email: false

sudo: false #有定制化开发环境需要，默认false，不开启容器，编译效率高

before_install: 
  - pip install codecov 
  - pip install coverage
  - pip install beautifulsoup4
  - pip install requests

install: true #跳过install

  
script: 
  - coverage run "movie.py"
  - coverage run "raspberry pi/test.py"
  

after_success:
  - codecov #运行codecov
